export const category_data = 
[
{id: 1, category: 'Advertisements Design'},
{id: 2, category: 'Brochure & Catalogue Design'},
{id: 3, category: 'Business Cards Design'},
{id: 4, category: 'Power Point Design'},
{id: 5, category: 'Flyers Design'},
{id: 6, category: 'Infographics & Flowcharts Design'},
{id: 7, category: 'Label & Packaging Design'},
{id: 8, category: 'Logo Design'},
{id: 9, category: 'Social Media Banners Design'},
{id: 10, category: 'Magazines Design'},
{id: 11, category: 'Poster Design'},
{id: 12, category: 'Standee & Billboards Design'},
{id: 13, category: 'Music Album Covers Design'},
{id: 14, category: 'Web Headers & Banners Design'},
{id: 15, category: 'Stationery Design'},
{id: 16, category: 'Invitation & Greetings Design'},
{id: 17, category: 'Emailer & Newsletter Design'},
{id: 18, category: 'Business Folder Design'},
{id: 19, category: 'Menu Design'},
{id: 20, category: 'Book Cover Design'},
{id: 21, category: 'Postcards Design'},
{id: 22, category: 'T-Shirts Design'},
]

// export const work_data = [
//     { id: 1, image: require('../assets/work/Fried.png'), title: 'Fried Turkeys', subTitle: 'Advertisements Design' },
//     { id: 2, image: require('../assets/work/Carolyn.png'), title: 'Carolyn Kimber', subTitle: 'Advertisements Design' },
//     { id: 3, image: require('../assets/work/Hygienitech.png'), title: 'Hygienitech', subTitle: 'Brochure & Catalogue Design' },
//     { id: 4, image: require('../assets/work/Avantgrade.png'), title: 'Avantgrade', subTitle: 'Business Cards Design' },
//     { id: 5, image: require('../assets/work/Panoroof.png'), title: 'Panoroof', subTitle: 'Flyers Design' },
//     { id: 6, image: require('../assets/work/Firefactory.png'), title: 'Firefactory', subTitle: 'Flyers Design' },
//     { id: 7, image: require('../assets/work/Business-Individual.png'), title: 'Business Individual', subTitle: 'Infographics & Flowcharts' },
//     { id: 8, image: require('../assets/work/Giovane-Skin.png'), title: 'Giovane Skin', subTitle: 'Label & Packaging Design' },
//     { id: 9, image: require('../assets/work/Nascent-Breach.png'), title: 'Nascent Breach', subTitle: 'Logo Design' },
//     { id: 10, image: require('../assets/work/Dollarsaver.png'), title: 'Dollarsaver', subTitle: 'Magazines Design' },
// ]