export const category_data = 
[
{id: 1, category: 'Advertisements Design'},
{id: 2, category: 'Brochure & Catalogue Design'},
{id: 3, category: 'Business Cards Design'},
{id: 4, category: 'Power Point Design'},
{id: 5, category: 'Flyers Design'},
{id: 6, category: 'Infographics & Flowcharts Design'},
{id: 7, category: 'Label & Packaging Design'},
{id: 8, category: 'Logo Design'},
{id: 9, category: 'Social Media Banners Design'},
{id: 10, category: 'Magazines Design'},
{id: 11, category: 'Poster Design'},
{id: 12, category: 'Standee & Billboards Design'},
{id: 13, category: 'Music Album Covers Design'},
{id: 14, category: 'Web Headers & Banners Design'},
{id: 15, category: 'Stationery Design'},
{id: 16, category: 'Invitation & Greetings Design'},
{id: 17, category: 'Emailer & Newsletter Design'},
{id: 18, category: 'Business Folder Design'},
{id: 19, category: 'Menu Design'},
{id: 20, category: 'Book Cover Design'},
{id: 21, category: 'Postcards Design'},
{id: 22, category: 'T-Shirts Design'},
]
